name: "svc"
port: "80"
target_port: "80"

staging:
    name: "my-staging-service"
    container_name: "my-staging-service-container"

production:
    name: "my-service"
    container_name: "my-serivce-container"
