apiVersion: v1
kind: Service
metadata:
  name: my-staging-service
spec:
  selector:
    app: my-staging-service
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-staging-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-staging-service
  strategy:
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: my-staging-service
      name: my-staging-service
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: my-staging-service-container
        env:
          - name: PORT
            value: "80"
        ports:
          - containerPort: 8080
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30